### ISSUE TITLE
Describe in the README file that the package is available in Package Control

### ISSUE THREAD

**Issue by taylon** [vivait/SublimeAutoSemiColon#10]
When I saw the package for the first time I installed that manually using Git. After that I realize that it was available at PackageControl which makes it much easier to install.

It would be nice if PackageControl was described in the Instalation section of the README file.

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that our Sublime loving developers went on to use other tooling some time ago and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
