### ISSUE TITLE
We need more possibilities

### ISSUE THREAD

**Issue by yckart** [vivait/SublimeAutoSemiColon#12]
# Javascript
## Functions
- [ ] ; function ()
- [ ] function ; ()
- [x] function ( ; arg)
- [ ] function (a;rg)
- [x] function (arg;)
- [x] } ; )
- [ ] ; })
### Variables
- [ ] ; var foo =
- [ ] var ; foo =
- [ ] var foo ; =
- [ ] var foo = ;
### Object properties (dot notation)
- [ ] ; this.foo =
- [ ] this ; .foo =
- [ ] this. ; foo =
- [ ] this.foo ; =
- [ ] this.foo = ;
### Object properties (bracket notation)
- [ ] ; this[foo] =
- [ ] this ; [foo] =
- [ ] this[ ; foo] =
- [ ] this[foo ; ] =
- [ ] this[foo] ; =

**Comment by pradyunsg** [comment]
I'm not so sure about them all...

It should be easy enough to make a <kbd>ctrl</kbd>+<kbd>;</kbd> bound macro which does the job pretty well for these other cases.

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that our Sublime loving developers went on to use other tooling some time ago and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
