### ISSUE TITLE
Atom port

### ISSUE THREAD

**Issue by stdavis** [vivait/SublimeAutoSemiColon#15]
Is there an atom port of this package?

**Comment by pradyunsg** [comment]
This is literally a 32 line package. I'm pretty sure almost anyone can port this over to Atom.

~Just Saying.

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that our Sublime loving developers went on to use other tooling some time ago and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
