### ISSUE TITLE
Compatible with Sublime Text 3?

### ISSUE THREAD

**Issue by Luc45** [vivait/SublimeAutoSemiColon#16]
Is this plugin compatible with ST3?

I couldn't make it work, neither through package control or manually.

**Comment by cmalard** [comment]
Works fine here, build 3126

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that our Sublime loving developers went on to use other tooling some time ago and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
